#server:
#  port: 8082
#  servlet:
#    session.timeout: 60000
#    contextpath: /

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/res?serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations:
        - classpath*:schema-all.sql
      data-locations:
        - classpath*:data-all.sql
      username: root
      password: 123456
      mode: NEVER     #*****注意它的取值

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印